package database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lptiyu.tanke.entity.greendao.LocationResult;

import database.LocationResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationResultDaoConfig;

    private final LocationResultDao locationResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationResultDaoConfig = daoConfigMap.get(LocationResultDao.class).clone();
        locationResultDaoConfig.initIdentityScope(type);

        locationResultDao = new LocationResultDao(locationResultDaoConfig, this);

        registerDao(LocationResult.class, locationResultDao);
    }
    
    public void clear() {
        locationResultDaoConfig.clearIdentityScope();
    }

    public LocationResultDao getLocationResultDao() {
        return locationResultDao;
    }

}
