package com.lptiyu.tanke.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lptiyu.tanke.database.Message;
import com.lptiyu.tanke.database.MessageList;

import com.lptiyu.tanke.database.MessageDao;
import com.lptiyu.tanke.database.MessageListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig messageListDaoConfig;

    private final MessageDao messageDao;
    private final MessageListDao messageListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        messageListDaoConfig = daoConfigMap.get(MessageListDao.class).clone();
        messageListDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        messageListDao = new MessageListDao(messageListDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(MessageList.class, messageListDao);
    }
    
    public void clear() {
        messageDaoConfig.getIdentityScope().clear();
        messageListDaoConfig.getIdentityScope().clear();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public MessageListDao getMessageListDao() {
        return messageListDao;
    }

}
