package com.lptiyu.tanke.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBTASK_RECORD".
 */
public class DBTaskRecord {

    private Long id;
    private String ftime;
    private String taskId;
    private String exp;

    public DBTaskRecord() {
    }

    public DBTaskRecord(Long id) {
        this.id = id;
    }

    public DBTaskRecord(Long id, String ftime, String taskId, String exp) {
        this.id = id;
        this.ftime = ftime;
        this.taskId = taskId;
        this.exp = exp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFtime() {
        return ftime;
    }

    public void setFtime(String ftime) {
        this.ftime = ftime;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getExp() {
        return exp;
    }

    public void setExp(String exp) {
        this.exp = exp;
    }

}
