package com.lptiyu.tanke.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    /** Not-null value. */
    private String alert;
    private String title;
    private Long time;
    private Integer type;
    private String image;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String alert, String title, Long time, Integer type, String image) {
        this.id = id;
        this.alert = alert;
        this.title = title;
        this.time = time;
        this.type = type;
        this.image = image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAlert() {
        return alert;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

}
