package com.lptiyu.tanke.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PUSH_MESSAGE".
 */
public class PushMessage {

    private Long id;
    /** Not-null value. */
    private String alert;
    private String title;
    private String url;
    private String image;
    private Long time;
    private Integer type;
    private Boolean isRead;

    public PushMessage() {
    }

    public PushMessage(Long id) {
        this.id = id;
    }

    public PushMessage(Long id, String alert, String title, String url, String image, Long time, Integer type, Boolean isRead) {
        this.id = id;
        this.alert = alert;
        this.title = title;
        this.url = url;
        this.image = image;
        this.time = time;
        this.type = type;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAlert() {
        return alert;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
