package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lptiyu.tanke.entity.greendao.DRLocalData;
import com.lptiyu.tanke.entity.greendao.LocationResult;

import greendao.DRLocalDataDao;
import greendao.LocationResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dRLocalDataDaoConfig;
    private final DaoConfig locationResultDaoConfig;

    private final DRLocalDataDao dRLocalDataDao;
    private final LocationResultDao locationResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dRLocalDataDaoConfig = daoConfigMap.get(DRLocalDataDao.class).clone();
        dRLocalDataDaoConfig.initIdentityScope(type);

        locationResultDaoConfig = daoConfigMap.get(LocationResultDao.class).clone();
        locationResultDaoConfig.initIdentityScope(type);

        dRLocalDataDao = new DRLocalDataDao(dRLocalDataDaoConfig, this);
        locationResultDao = new LocationResultDao(locationResultDaoConfig, this);

        registerDao(DRLocalData.class, dRLocalDataDao);
        registerDao(LocationResult.class, locationResultDao);
    }
    
    public void clear() {
        dRLocalDataDaoConfig.clearIdentityScope();
        locationResultDaoConfig.clearIdentityScope();
    }

    public DRLocalDataDao getDRLocalDataDao() {
        return dRLocalDataDao;
    }

    public LocationResultDao getLocationResultDao() {
        return locationResultDao;
    }

}
